import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState, { GlobalContext } from '@/context'
import Navbar from '@/components/Navbar'
//mport Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <GlobalState>
        <Navbar />
        <main>
           {children}
        </main>
        {/*<Footer />*/}
      </GlobalState>
    </html>
  )
}
